<?php
require_once __DIR__ . '/core/autocontrollo_settings.php';
require_once __DIR__.'/core/auth.php'; require_once __DIR__.'/core/security.php'; require_once __DIR__.'/core/settings.php'; require_once __DIR__.'/core/autocontrollo_fire.php';
require_login(); $user=current_user(); if(!$user||!autocontrollo_user_can_perform($user, 'fire')){http_response_code(403);exit('Accesso negato.');}
$env=require __DIR__.'/config/env.php'; $base=rtrim($env['app']['base_url']??'','/'); $pdo=db(); ensure_autocontrollo_fire_inspections_tables($pdo); $range=get_summer_season_range($pdo); $today=new DateTimeImmutable('today',new DateTimeZone('Europe/Rome')); $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  if(!csrf_check((string)($_POST['csrf']??''))){http_response_code(400);exit('Token CSRF non valido.');}
  try{$action=(string)($_POST['action']??'');
    if($action==='start'){ $id=autocontrollo_fire_start($pdo,$range,(string)($_POST['scheduled_date']??''),(int)$user['id']); header('Location: '.$base.'/autocontrollo_antincendio.php?inspection='.$id);exit; }
    if($action==='check'){ $inspectionId=(int)($_POST['inspection_id']??0);$resultId=(int)($_POST['result_id']??0);$suitable=(string)($_POST['is_suitable']??''); if(!in_array($suitable,['0','1'],true))throw new InvalidArgumentException('Indicare l’esito della verifica.');
      $stmt=$pdo->prepare("UPDATE autocontrollo_fire_inspection_results r JOIN autocontrollo_fire_inspections i ON i.id=r.inspection_id SET r.is_suitable=?,r.checked_at=NOW() WHERE r.id=? AND r.inspection_id=? AND r.checked_at IS NULL AND i.status='in_corso'");$stmt->execute([(int)$suitable,$resultId,$inspectionId]);if($stmt->rowCount()!==1)throw new RuntimeException('Passaggio non valido o già registrato.');
      $stmt=$pdo->prepare('SELECT COUNT(*) FROM autocontrollo_fire_inspection_results WHERE inspection_id=? AND checked_at IS NULL');$stmt->execute([$inspectionId]);if((int)$stmt->fetchColumn()===0){$pdo->prepare("UPDATE autocontrollo_fire_inspections SET status='completata',completed_at=NOW() WHERE id=? AND status='in_corso'")->execute([$inspectionId]);autocontrollo_fire_send_report($pdo,$inspectionId);header('Location: '.$base.'/autocontrollo_antincendio.php?completed='.$inspectionId);exit;} header('Location: '.$base.'/autocontrollo_antincendio.php?inspection='.$inspectionId);exit;
    } throw new InvalidArgumentException('Azione non valida.');
  }catch(Throwable $e){$error=$e->getMessage();}
}
$inspectionId=(int)($_GET['inspection']??($_POST['inspection_id']??0));if($inspectionId<=0){$stmt=$pdo->prepare("SELECT id FROM autocontrollo_fire_inspections WHERE season_start=? AND season_end=? AND status='in_corso' ORDER BY scheduled_date LIMIT 1");$stmt->execute([$range['start']??'',$range['end']??'']);$inspectionId=(int)($stmt->fetchColumn()?:0);}
$active=null;$current=null;$results=[];$progress=[0,0];if($inspectionId){$stmt=$pdo->prepare('SELECT * FROM autocontrollo_fire_inspections WHERE id=?');$stmt->execute([$inspectionId]);$active=$stmt->fetch(PDO::FETCH_ASSOC);if($active&&$active['status']==='in_corso'){$stmt=$pdo->prepare('SELECT * FROM autocontrollo_fire_inspection_results WHERE inspection_id=? ORDER BY sort_order');$stmt->execute([$inspectionId]);$results=$stmt->fetchAll(PDO::FETCH_ASSOC);foreach($results as $row)if($current===null&&$row['checked_at']===null)$current=$row;$progress=[count($results),count(array_filter($results,static fn($row)=>$row['checked_at']!==null))];}}
$stmt=$pdo->prepare("SELECT i.*,u.email operator_email,TRIM(CONCAT_WS(' ',NULLIF(u.nome,''),NULLIF(u.cognome,''))) operator_name,COUNT(r.id) extinguisher_count,COALESCE(SUM(r.is_suitable=0),0) anomaly_count FROM autocontrollo_fire_inspections i LEFT JOIN users u ON u.id=i.operator_id LEFT JOIN autocontrollo_fire_inspection_results r ON r.inspection_id=i.id WHERE i.season_start=? AND i.season_end=? GROUP BY i.id ORDER BY i.scheduled_date DESC");$stmt->execute([$range['start']??'',$range['end']??'']);$inspections=$stmt->fetchAll(PDO::FETCH_ASSOC);
$completedDates=[];foreach($inspections as $item)if($item['status']==='completata')$completedDates[]=$item['scheduled_date'];$nextDate=autocontrollo_fire_next_date(autocontrollo_fire_schedule($range),$completedDates);
$viewId=(int)($_GET['view']??0);$viewResults=[];if($viewId){$stmt=$pdo->prepare('SELECT * FROM autocontrollo_fire_inspection_results WHERE inspection_id=? ORDER BY sort_order');$stmt->execute([$viewId]);$viewResults=$stmt->fetchAll(PDO::FETCH_ASSOC);}
$title='Autocontrollo Antincendio';include __DIR__.'/partials/header.php';?>
<div class="d-flex flex-column flex-sm-row justify-content-between align-items-sm-center gap-2 mb-4"><div><div class="text-muted small text-uppercase fw-semibold">Autocontrollo</div><h1 class="h4 mb-0"><i class="bi bi-fire me-1"></i>Antincendio</h1></div><a class="btn btn-outline-danger" href="<?=e($base)?>/reports/autocontrollo_fire_pdf.php?season=1"><i class="bi bi-file-earmark-pdf me-1"></i>Esporta PDF stagione</a></div>
<?php if($error):?><div class="alert alert-danger"><?=e($error)?></div><?php endif;if(isset($_GET['completed'])):?><div class="alert alert-success">Procedura completata e rapporto inviato agli utenti Amministrazione.</div><?php endif;?>
<div class="alert alert-info"><strong>Controllo visivo del responsabile:</strong> verificare che ogni estintore sia integro, visibile, libero da ostacoli e con il manometro nella zona verde.</div>
<?php if($active&&$current):$percent=(int)round($progress[1]/max(1,$progress[0])*100);?>
<div class="card shadow-sm border-primary mx-auto" style="max-width:720px"><div class="card-body p-3 p-md-4"><div class="d-flex justify-content-between"><span class="badge text-bg-primary">Estintore <?=$progress[1]+1?> di <?=$progress[0]?></span><span><?=$percent?>%</span></div><div class="progress my-2 mb-4"><div class="progress-bar" style="width:<?=$percent?>%"></div></div><div class="text-muted"><?=e(ucfirst($current['extinguisher_type']))?> · <?=e($current['capacity_kg'])?> Kg</div><h2 class="display-6">ID <?=e($current['extinguisher_label'])?></h2>
<div class="table-responsive my-4"><table class="table table-sm"><thead><tr><th>ID Estintore</th><th>Verifica Positiva</th></tr></thead><tbody><?php foreach($results as $row):?><tr class="<?=(int)$row['id']===(int)$current['id']?'table-primary':''?>"><td><?=e($row['extinguisher_label'])?></td><td><?=$row['checked_at']===null?'—':((int)$row['is_suitable']?'Sì':'<strong class="text-danger">NO</strong>')?></td></tr><?php endforeach;?></tbody></table></div>
<form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="check"><input type="hidden" name="inspection_id" value="<?=(int)$active['id']?>"><input type="hidden" name="result_id" value="<?=(int)$current['id']?>"><fieldset><legend class="h5">L’estintore ha superato la verifica?</legend><div class="row g-2 mb-3"><div class="col-6"><input class="btn-check" type="radio" name="is_suitable" id="fireYes" value="1" required><label class="btn btn-outline-success btn-lg w-100" for="fireYes">Sì</label></div><div class="col-6"><input class="btn-check" type="radio" name="is_suitable" id="fireNo" value="0" required><label class="btn btn-outline-danger btn-lg w-100" for="fireNo">No</label></div></div></fieldset><button class="btn btn-primary btn-lg w-100">Salva e continua</button></form></div></div>
<?php else:?><div class="card shadow-sm mb-4"><div class="card-body"><h2 class="h5">Prossimo controllo mensile</h2><?php if(empty($range['start'])||empty($range['end'])):?><div class="alert alert-warning mb-0">Configurare le date di apertura e chiusura della stagione.</div><?php elseif(!$nextDate):?><div class="alert alert-success mb-0">Tutti i controlli stagionali sono completati.</div><?php else:$available=$nextDate<=$today->format('Y-m-d');?><div class="fs-4 fw-semibold mb-3"><?=e((new DateTimeImmutable($nextDate))->format('d/m/Y'))?></div><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="start"><input type="hidden" name="scheduled_date" value="<?=e($nextDate)?>"><button class="btn btn-primary" <?=$available?'':'disabled'?>><?=$available?'Avvia procedura':'Non ancora disponibile'?></button></form><?php endif;?></div></div><?php endif;?>
<div class="card shadow-sm mt-4"><div class="card-header bg-white"><h2 class="h5 mb-0">Rilevazioni effettuate</h2></div><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Data e ora</th><th>Scadenza</th><th>Operatore</th><th>Estintori</th><th>Anomalie da risolvere</th><th>Stato</th><th></th></tr></thead><tbody><?php if(!$inspections):?><tr><td colspan="7" class="text-center text-muted py-4">Nessuna procedura avviata.</td></tr><?php endif;foreach($inspections as $item):?><tr><td><?=e((new DateTimeImmutable($item['started_at']))->format('d/m/Y H:i'))?></td><td><?=e((new DateTimeImmutable($item['scheduled_date']))->format('d/m/Y'))?></td><td><?=e($item['operator_name']?:($item['operator_email']??'—'))?></td><td><?=(int)$item['extinguisher_count']?></td><td><?php if((int)$item['anomaly_count']):?><span class="badge text-bg-danger"><?=(int)$item['anomaly_count']?> anomalie</span><?php else:?><span class="badge text-bg-success">Nessuna</span><?php endif;?></td><td><?=e($item['status'])?></td><td class="text-end text-nowrap"><a class="btn btn-sm btn-outline-danger" href="<?=e($base)?>/reports/autocontrollo_fire_pdf.php?id=<?=(int)$item['id']?>" title="Esporta rilievo in PDF" aria-label="Esporta rilievo #<?=(int)$item['id']?> in PDF"><i class="bi bi-file-earmark-pdf"></i></a> <a class="btn btn-sm btn-outline-secondary" href="?view=<?=(int)$item['id']?>#dettaglio">Dettagli</a><?php if($item['status']==='in_corso'):?> <a class="btn btn-sm btn-primary" href="?inspection=<?=(int)$item['id']?>">Continua</a><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div>
<?php if($viewResults):?><div class="card shadow-sm mt-3" id="dettaglio"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>ID Estintore</th><th>Tipologia</th><th>Capacità</th><th>Verifica Positiva</th></tr></thead><tbody><?php foreach($viewResults as $row):?><tr class="<?=$row['is_suitable']!==null&&!(int)$row['is_suitable']?'table-danger':''?>"><td><?=e($row['extinguisher_label'])?></td><td><?=e(ucfirst($row['extinguisher_type']))?></td><td><?=e($row['capacity_kg'])?> Kg</td><td><?=$row['is_suitable']===null?'—':((int)$row['is_suitable']?'Sì':'<strong>NO — Anomalia</strong>')?></td></tr><?php endforeach;?></tbody></table></div></div><?php endif;include __DIR__.'/partials/footer.php';?>
