<?php
use Dompdf\Dompdf;
use Dompdf\Options;
require_once __DIR__.'/../core/auth.php';require_once __DIR__.'/../core/settings.php';require_once __DIR__.'/../core/db.php';require_once __DIR__.'/../dompdf/vendor/autoload.php';
require_login();$user=current_user();if(!$user||!user_has_department($user,'Amministrazione')){http_response_code(403);exit('Accesso negato.');}
$pdo=db();ensure_autocontrollo_rodent_inspections_tables($pdo);$inspectionId=(int)($_GET['id']??0);$seasonExport=(string)($_GET['season']??'')==='1';if($inspectionId<=0&&!$seasonExport){http_response_code(400);exit('Richiesta PDF non valida.');}
if($inspectionId>0){$where='WHERE i.id=?';$params=[$inspectionId];}else{$range=get_summer_season_range($pdo);if(empty($range['start'])||empty($range['end'])){http_response_code(400);exit('Stagione non configurata.');}$where='WHERE i.season_start=? AND i.season_end=?';$params=[$range['start'],$range['end']];}
$stmt=$pdo->prepare("SELECT i.*,u.email operator_email,TRIM(CONCAT_WS(' ',NULLIF(u.nome,''),NULLIF(u.cognome,''))) operator_name FROM autocontrollo_rodent_inspections i LEFT JOIN users u ON u.id=i.operator_id $where ORDER BY i.scheduled_date,i.started_at");$stmt->execute($params);$inspections=$stmt->fetchAll(PDO::FETCH_ASSOC);if($inspectionId>0&&!$inspections){http_response_code(404);exit('Procedura non trovata.');}$resultStmt=$pdo->prepare('SELECT * FROM autocontrollo_rodent_inspection_results WHERE inspection_id=? ORDER BY sort_order');$escape=static fn($value):string=>htmlspecialchars((string)$value,ENT_QUOTES,'UTF-8');$yesNo=static fn($value):string=>$value===null?'—':((int)$value?'Sì':'No');ob_start();
?><!doctype html><html lang="it"><head><meta charset="utf-8"><style>body{font-family:DejaVu Sans,sans-serif;color:#1f2937;font-size:9px}h1{font-size:20px;color:#0d6efd;margin:0 0 4px}.period{color:#6b7280;margin-bottom:16px}.inspection{margin-bottom:18px;page-break-inside:avoid}.meta{margin-bottom:7px}.results{width:100%;border-collapse:collapse}.results th{background:#e9ecef;text-align:left}.results th,.results td{border:1px solid #adb5bd;padding:5px}.alert{background:#fff3cd}.signatures{margin-top:28px;width:100%;page-break-inside:avoid}.signatures td{width:50%;padding-top:12px;vertical-align:top}.line{display:inline-block;border-bottom:1px solid #374151;min-width:170px;height:14px}.footer{margin-top:18px;color:#6b7280;text-align:right;font-size:8px}</style></head><body><h1>Autocontrollo Derattizzazione</h1><div class="period"><?=$seasonExport?'Report cumulativo della stagione':'Procedura #'.(int)$inspectionId?></div><?php if(!$inspections):?><div>Nessuna procedura presente nella stagione.</div><?php endif;foreach($inspections as$inspection):$resultStmt->execute([$inspection['id']]);$results=$resultStmt->fetchAll(PDO::FETCH_ASSOC);?><div class="inspection"><div class="meta"><strong>Scadenza:</strong> <?=$escape((new DateTimeImmutable($inspection['scheduled_date']))->format('d/m/Y'))?> · <strong>Eseguito:</strong> <?=$escape((new DateTimeImmutable($inspection['started_at']))->format('d/m/Y H:i'))?> · <strong>Operatore:</strong> <?=$escape($inspection['operator_name']?:($inspection['operator_email']??'—'))?> · <strong>Stato:</strong> <?=$escape($inspection['status'])?></div><table class="results"><thead><tr><th>Trappola</th><th>Esca presente</th><th>Esca mangiata</th><th>Esca sostituita</th><th>Verificata</th></tr></thead><tbody><?php foreach($results as$row):$alert=(int)($row['bait_eaten']??0)===1;?><tr class="<?=$alert?'alert':''?>"><td><?=$escape($row['trap_location'])?></td><td><?=$yesNo($row['bait_present'])?></td><td><?=$yesNo($row['bait_eaten'])?></td><td><?=$yesNo($row['bait_replaced'])?></td><td><?=$row['checked_at']?$escape((new DateTimeImmutable($row['checked_at']))->format('d/m/Y H:i')):'—'?></td></tr><?php endforeach;?></tbody></table></div><?php endforeach;?><table class="signatures"><tr><td><strong>Data Estrapolazione:</strong> <?=date('d/m/Y')?></td><td><strong>Firma del Responsabile:</strong> <span class="line"></span></td></tr></table><div class="footer">Documento esportato da Dojo</div></body></html><?php
$html=ob_get_clean();$options=new Options();$options->set('isRemoteEnabled',false);$pdf=new Dompdf($options);$pdf->loadHtml($html,'UTF-8');$pdf->setPaper('A4','portrait');$pdf->render();$filename=$seasonExport?'autocontrollo-derattizzazione-stagione.pdf':'autocontrollo-derattizzazione-'.$inspectionId.'.pdf';$pdf->stream($filename,['Attachment'=>true]);
